"""initial migration

Revision ID: 5c93e2aa0cc8
Revises: 
Create Date: 2025-12-14 18:48:31.126350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c93e2aa0cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index('idx_pupils_academic_year_id')
        batch_op.create_index(batch_op.f('ix_pupils_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.drop_constraint('fk_pupils_academic_year', type_='foreignkey')
        batch_op.create_foreign_key(None, 'academic_years', ['academic_year_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_pupils_academic_year', 'academic_years', ['academic_year_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_pupils_academic_year_id'))
        batch_op.create_index('idx_pupils_academic_year_id', ['academic_year_id'], unique=False)

    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
