"""Add attendance table

Revision ID: 8ab4e2f861bd
Revises: fa6657eebaa1
Create Date: 2025-12-15 20:01:07.627218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab4e2f861bd'
down_revision = 'fa6657eebaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=80), nullable=False),
    sa.Column('stream_id', sa.String(length=120), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupils.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pupil_id', 'attendance_date', name='unique_pupil_date_attendance')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_pupil_id'), ['pupil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_stream_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_pupil_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_class_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_academic_year_id'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
