"""Add attendance table

Revision ID: fa6657eebaa1
Revises: c7c8118d161e
Create Date: 2025-12-15 19:49:49.439048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6657eebaa1'
down_revision = 'c7c8118d161e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_index('ix_pupils_class_stream')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.create_index('ix_pupils_class_stream', ['class_admitted', 'stream'], unique=False)

    # ### end Alembic commands ###
